# Pytorch Introduction

![Pytorch](Images/PyTorch.png)

- Easy to use deep learning framework
- Good for prototyping and production as well (with 1.0 coming)
- Numpy on steroids and more Pythonic
- Easy to debug

In [6]:
import torch
import numpy as np

## Tensor Manipulation

Lets create a 2D random tensor and try some basic indexing operations

In [3]:
a = torch.randn(7, 7, dtype=torch.double)
a

tensor([[ 1.0008, -0.4380,  1.4690, -0.4383,  0.6685,  0.3608,  1.3831],
        [ 1.8864, -0.9329, -0.7539, -1.1748,  0.3979,  1.1239, -1.7193],
        [ 0.7344,  0.3453,  1.6576, -0.2390,  1.7616,  0.1066,  1.4948],
        [-0.4147, -0.0388, -0.2329,  0.8230,  1.0318,  1.8783,  0.0882],
        [ 0.8152, -0.6244,  0.8815, -0.9721,  2.0163,  0.1875,  2.0903],
        [-0.6004, -0.2341,  0.8573,  0.6282,  0.5065, -1.0670,  0.5260],
        [ 0.7750,  0.8317, -1.5540, -0.2375,  1.5357,  1.5986, -0.8466]],
       dtype=torch.float64)

In [4]:
a[:, :] = 0   # Assign zeros everywhere in the matrix.
a[3, 3] = 1   # Assign one in position 3, 3
a

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

Lets create a torch tensor from Numpy array

In [7]:
x1 = np.ndarray(shape=(2,3), dtype=int,buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)
x2

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

Lets see another basic operation namely concatenation and reshape

In [9]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0)
z1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

In [10]:
z1 = torch.cat([x,y],dim=1)
z1

tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]])

Lets see how to change the shape now. Lets shape to 6*2

In [12]:
z1.view(6,2)

tensor([[ 1.,  2.],
        [ 3., -1.],
        [-2., -3.],
        [ 4.,  5.],
        [ 6., -4.],
        [-5., -6.]])

## Tensor Operations

Lets see 2 most important operations in action namely addition and multiplication


In [13]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)
add

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [21]:
x1 = torch.randn((3,4))
x2 = torch.randn((4,5))
mul = torch.mm(x1,x2)

In [22]:
mul.shape

torch.Size([3, 5])

## Autograd

Gradients represent the rate of change in function. They are used in neural network for optimising the network to predict the correct output. Gradient is calculated in neural network optimization process by calculating the derivative of the function to be optimised. PyTorch uses autograd package to provide automatic differentiation for all operations on Tensor. Lets see autograd in action

In [23]:
x = torch.tensor([2,2],dtype=torch.float32,requires_grad = True)

Now lets perform some operations on this tensor

In [24]:
y = x * x

Since y was created as aresult of operation on x, y has grad_fn attribute so we can calculate the derivative of y wrt x

In [25]:
y.grad_fn

Lets perform some more operations on y

In [26]:
y = 3*y +2

In [27]:
y = y.mean()
y

tensor(14., grad_fn=<MeanBackward1>)

Now suppose we want to optimize y and for that we want to calculate the gradient of y wrt x. Pytorch calculates the gradient automatically as we define and execute the operation. This is due to its nature of building Dynamic Computation graphs

In [28]:
y.backward()

After we have called the backward method that computes the gradient we have the gradient for each of the input stored in the grad attribute

In [29]:
x.grad

tensor([6., 6.])

Here we had the function  y = 3$x^2$ + 2. So gradient of y wrt x dy/dx is 3*2 = 6